#!/usr/bin/with-contenv bash
# ==============================================================================
# Start EmberZNet Zigbee Daemon - TCP bridge via socat
# ==============================================================================
set -euo pipefail
source /etc/bashlog/log.sh

EZSP_PORT="${EZSP_LISTEN_PORT:-20108}"
log 'info' "Starting zigbeed-tcp on port ${EZSP_PORT}..."
exec /usr/bin/socat TCP-LISTEN:${EZSP_PORT},reuseaddr,fork FILE:/tmp/ttyZigbee,raw,echo=0,b115200